const array = [
  {
    category: "SmallSize",
    itemName: "Small size Locker",
    price: "1199",
    img: "https://img2.exportersindia.com/product_images/bc-small/2022/11/11434074/accura-electronic-safety-locker-iris-6145-n-1669814534-6650110.jpeg",
    des: "Multipurpose locker for home use ",
  },
  {
    category: "Jewellery",
    itemName: "Jewellery Locker",
    price: "1199",
    img: "https://image.made-in-china.com/202f0j00heHUoVnCSjqy/2020-Big-Digital-Safe-Deposit-Locker-for-Home-Online-Wholesale-1300mm-High.jpg",
    des: "Jewellery Locker for shops. It is very safe place for jewellery ",
  },
  {
    category: "jewellery",
    itemName: "Jewellery Locker",
    price: "2999",
    img: "https://5.imimg.com/data5/SELLER/Default/2021/9/HU/EX/LT/34642978/safe-security-home-locker-500x500.jpg",
    des: "Jewellery Locker for shops. It is very safe place for jewellery ",
  },
  {
    category: "Digital",
    itemName: "Digital Locker",
    price: "1199",
    img: "https://rukminim2.flixcart.com/image/850/1000/xif0q/safe-locker/3/e/n/aps-1113-plantex-original-imagv42gxf7wh5z7.jpeg?q=20&crop=false",
    des: "It gives extra security to our important documents and ornaments ",
  },
  {
    category: "Mini",
    itemName: "Digital Mini Locker",
    price: "1099",
    img: "https://sanushaa.in/wp-content/uploads/2019/10/godrej-nx-15-litres-digital-electronic-safe-locker-ebony_4.jpg",
    des: "It gives extra security to our important documents and ornaments ",
  },
  {
    category: "SmallSize",
    itemName: "Small Size Locker",
    price: "1199",
    img: "https://img2.exportersindia.com/product_images/bc-small/2022/11/11434074/accura-electronic-safety-locker-iris-6145-n-1669814534-6650110.jpeg",
    des: "Multipurpose locker for home use ",
  },
  {
    category: "Mini",
    itemName: "Digital Mini Locker",
    price: "1099",
    img: "https://sanushaa.in/wp-content/uploads/2019/10/godrej-nx-15-litres-digital-electronic-safe-locker-ebony_4.jpg",
    des: "It gives extra security to our important documents and ornaments ",
  },
  {
    category: "Jewellery",
    itemName: "Jewellery Locker",
    price: "1199",
    img: "https://image.made-in-china.com/202f0j00heHUoVnCSjqy/2020-Big-Digital-Safe-Deposit-Locker-for-Home-Online-Wholesale-1300mm-High.jpg",
    des: "Jewellery Locker for shops. It is very safe place for jewellery ",
  },
  {
    category: "Minimal",
    itemName: "Normal Size Locker",
    price: "1199",
    img: "https://mahmayi.com/media/catalog/product/cache/ddb4980aa3ce07e0aeb4d6c5eb231489/t/i/tijori_88_2k_4__2.jpg",
  },
  {
    category: "Digital",
    itemName: "Digital Locker",
    price: "1199",
    img: "https://5.imimg.com/data5/SELLER/Default/2021/8/QT/GX/BG/15032120/godrej-matrix-electronic-safe-250x250.jpg",
    des: "It gives extra security to our important documents and ornaments ",
  },
  {
    category: "Minimal",
    itemName: "Normal Size Locker",
    price: "1199",
    img: "https://mahmayi.com/media/catalog/product/cache/ddb4980aa3ce07e0aeb4d6c5eb231489/t/i/tijori_88_2k_4__2.jpg",
    des: "It gives extra security to our important documents and ornaments ",
  },
  {
    category: "Digital",
    itemName: "Digital Locker",
    price: "1199",
    img: "https://5.imimg.com/data5/SELLER/Default/2021/8/QT/GX/BG/15032120/godrej-matrix-electronic-safe-250x250.jpg",
    des: "It gives extra security to our important documents and ornaments ",
  },
];
